### ISSUE TITLE
WGAN generates data

### ISSUE THREAD

**Issue by gaoyacui** [BlingBlingss/VAE-CWGAN-GP#1]
Hello, I have some questions to ask you.I want to use GaN to generate data from other data sets. How to use my own data set?
I encountered many problems in the process of revision. I am a beginner.

**Comment by BlingBlingss** [comment]
So what's the problem?

**Comment by gaoyacui** [comment]
I would like to use your generation model to generate bearing data, of which there are 10 categories.In the process of changing the data set, I changed the corresponding parameters, such as 7 to 10.But there are still problems.
Such as

Traceback (most recent call last):
  File "D:/daima/myprogram/CWGAN/CWGAN_new.py", line 189, in <module>
    x_, y_ = load_data(select_number)
  File "D:/daima/myprogram/CWGAN/CWGAN_new.py", line 48, in load_data
    sample = TR_sample_temp['num']
KeyError: 'num'

There are also shape mismatch, (100,70) and other problems.

**Comment by BlingBlingss** [comment]
I just ran the code. The code can run through. You should modify the code input to fit your dataset.

**Comment by gaoyacui** [comment]
Thank you. I wonder if you could give me a comment on the code?
My coding skills are very poor. This means a lot to me. I would appreciate it if you could.
