### ISSUE TITLE
When I run the code, diagnostic-original.py, I run into the following problem.

### ISSUE THREAD

**Issue by gaoyacui** [BlingBlingss/VAE-CWGAN-GP#2]
file_name1 = "./temp_result/Diagnosis_"+str(select_number)+"Level"+str(level_num)+"_Accuracy_result.txt"
file_name2 = "./temp_result/Diagnosis_"+str(select_number)+"Level"+str(level_num)+"_f1_score_result.txt"

D:\anaconda\envs\tf1.15\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
Traceback (most recent call last):
  File "D:/daima/myprogram/VAE-CWGAN-GP-master/CWGAN/Diagnosis_original.py", line 161, in <module>
    RF_AC, SVM_AC, DT_AC, NB_AC, MLP_AC, KNN_AC, LG_AC = classify(train_data, train_label)
  File "D:/daima/myprogram/VAE-CWGAN-GP-master/CWGAN/Diagnosis_original.py", line 154, in classify
    with open(file_name1, "a") as f:
FileNotFoundError: [Errno 2] No such file or directory: './temp_result/Diagnosis_10Level1_Accuracy_result.txt'

Process finished with exit code 1

**Comment by BlingBlingss** [comment]
运行Main文件5次后，再运行test.py

**Comment by Arroganceem** [comment]
data有吗大佬个人学习用
